const set1 = [
  "ai",
  "airbnb",
  "amazon",
  "bandwidth",
  "big data",
  "bleeding edge",
  "blockchain",
  "break things",
  "bubble",
  "buzz",
  "circle back",
  "close the loop",
  "critical mass",
  "crushing it",
  "curated",
  "cutting edge",
  "decacorn",
  "disrupt",
  "disruptive",
  "facebook",
  "first mover advantage",
  "freemium",
  "game changer",
  "gamification",
  "gen-z",
  "google",
  "growth hacking",
  "guru",
  "hair on fire",
  "holy grail",
  "influencer",
  "innovative",
  "innovator",
  "instagram",
  "ipo",
  "iteration",
  "killing it",
  "launch party",
  "lean startup",
  "leverage",
  "low hanging fruit",
  "machine learning",
  "millenials",
  "mission critical",
  "move fast",
  "network effect",
  "niche market",
  "ninja",
  "pants on fire",
  "paradigm shift",
  "pivot",
  "ready to scale",
  "rockstar",
  "seamless",
  "seamlessly",
  "serial entrepreneur",
  "stealth",
  "sweat equity",
  "sync",
  "technology",
  "termsheet",
  "the cloud",
  "thought leader",
  "traction",
  "twitter",
  "uber",
  "unicorn",
  "vanity metrics",
  "virality",
  "visionary",
  "win-win",
  "wizard"
];

const set2 = [
  "a/b testing",
  "accelerator",
  "analytics",
  "assets",
  "backing",
  "beta",
  "buyer",
  "channels",
  "crowdfunding",
  "deck",
  "early adopters",
  "ecosystem",
  "exit",
  "hackathon",
  "handshake",
  "hockey stick",
  "incubator",
  "infographic",
  "infrastructure",
  "internet of things",
  "iot",
  "learning curve",
  "long tail",
  "market penetration",
  "market validation",
  "marketing",
  "monetization",
  "partnership",
  "platform",
  "product-market fit",
  "productivity",
  "scalable",
  "scale",
  "silo",
  "social proof",
  "stock",
  "user experience",
  "value proposition",
  "venture",
  "vesting period",
  "vr"
];

const set3 = [
  "advisor",
  "angel investor",
  "bootstrapped",
  "bootstrapping",
  "burn rate",
  "business plan",
  "business-to-consumer",
  "churn rate",
  "conversion",
  "customer",
  "entrepreneur",
  "equity",
  "focus",
  "founder",
  "founders",
  "funding",
  "hypothesis",
  "investor",
  "metrics",
  "mvp",
  "pitch",
  "runway",
  "seed round",
  "series a"
];

const convertData = array => {
  const finalArray = [];

  array.forEach(element => {
    const obj = {};
    obj["category"] = "MOSTLY HARMLESS";
    obj["word"] = element;
    obj["replace"] = "IF YOU MUST";
    finalArray.push(obj);
  });

  return finalArray;
};

console.log(convertData(set3));
